public class CalculatorConstructorTester {
	
	public static void main(String[] args) {
		
		System.out.println("Begin creating calaculator");
		
		CalculatorConstructor xyz = new CalculatorConstructor();
		System.out.println("brand name: "+ xyz.brand);
		
		CalculatorConstructor zen = new CalculatorConstructor("zen");
		System.out.println("the brand: "+zen.brand);
		
		int sum=zen.addition(1,2);
		System.out.println("The sum generated by zen: "+sum);
		int diff=zen.subtraction(4,5);
		System.out.println("The difference generated by zen: "+diff);
		int pro=zen.multiplication(6,7);
		System.out.println("The product generated by zen: "+pro);
		
		CalculatorConstructor casio = new CalculatorConstructor("Scientific",12);
		System.out.println("the size: "+casio.sizeInCm);
		System.out.println("the type: "+casio.type);
		
		diff=casio.subtraction(2,1);
		System.out.println("The diff generated by casio: "+diff);
		
		CalculatorConstructor citizen = new CalculatorConstructor("citizen",12,"General purpose",1000);
		System.out.println("the brand: "+citizen.brand);
		System.out.println("the size: "+citizen.sizeInCm);
		System.out.println("the type: "+citizen.type);
		System.out.println("the price :"+citizen.price);
		
		pro=citizen.multiplication(1,2);
		System.out.println("The product generated by citizen: "+pro);
		
		System.out.println("End creating calaculator");
	}

}

